uriygulak\BlogBundle\Entity\autor:
    type: entity
    table: null
    repositoryClass: uriygulak\BlogBundle\Repository\autorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
        old:
            type: integer
    lifecycleCallbacks: {  }
