<?php

namespace uriygulak\BlogBundle\Repository;

/**
 * autorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class autorRepository extends \Doctrine\ORM\EntityRepository
{
}
